version: '3.1'

services:
  dataplay-db:
    image: postgres:12
    container_name: dataplay-db
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dataplay
    volumes:
      - ./pgdata:/var/lib/postgresql/data
